name: place
version: '1.0-SNAPSHOT'
main: dk.milasholsting.place.Place
api-version: '1.21'
depend: ["WorldGuard"]
commands:
    test:
      description: a test command
      usage: /test
      permission: place.command.test